name: Wait for workflow

inputs:
  repository:
    required: true
    description: Repository name (e.g. romanrod/wait-for-woprkflp).
  worflow_name:
    required: true
    description: The name of the workflow the action will wait for.
  run_id:
    description: 'Id of workflow to wait for. If you used benc-uk/workflow-dispatch to dispatch, you can use ${{ steps.<step-name>.outputs.runId }}'
    required: true
  timeout:
    required: false
    description: Timeout in seconds.
    default: 600

runs:
  using: node16
  main: dist/index.js
